language: r
cache: packages
warnings_are_errors: true
sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

apt_packages:
  - r-cran-httr
  - librdf0

r_packages:
  - rmarkdown
