language: r
cache: packages
warnings_are_errors: true
sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - rmarkdown
  
apt_packages:
  - librdf0
  - librdf0-dev
